minVersion: 0.23.1
changelogPolicy: simple
targets:
  - name: gcs
    bucket: sentry-sdk-assets
    includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
    paths:
      - path: /sentry-cli/{{version}}/
        metadata:
          cacheControl: public, max-age=2592000
      - path: /sentry-cli/latest/
        metadata:
          cacheControl: public, max-age=600
  - name: npm
  - name: brew
    tap: getsentry/tools
    template: "class SentryCli < Formula\n  desc \"Sentry command-line client for\
      \ some generic tasks\"\n  homepage \"https://github.com/getsentry/sentry-cli\"\
      \n  version \"{{version}}\"\n  license \"BSD-3-Clause\"\n\n  if OS.mac?\n  \
      \  url \"https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Darwin-universal\"\
      \n    sha256 \"{{checksums.sentry-cli-Darwin-universal}}\"\n  elsif OS.linux?\n\
      \    if Hardware::CPU.arm?\n      if Hardware::CPU.is_64_bit?\n        url \"\
      https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Linux-aarch64\"\
      \n        sha256 \"{{checksums.sentry-cli-Linux-aarch64}}\"\n      else\n  \
      \      url \"https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Linux-armv7\"\
      \n        sha256 \"{{checksums.sentry-cli-Linux-armv7}}\"\n      end\n    elseif\
      \ Hardware::CPU.intel?\n      if Hardware::CPU.is_64_bit?\n        url \"https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Linux-x86_64\"\
      \n        sha256 \"{{checksums.sentry-cli-Linux-x86_64}}\"\n      else\n   \
      \     url \"https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Linux-i686\"\
      \n        sha256 \"{{checksums.sentry-cli-Linux-i686}}\"\n      end\n    else\n\
      \      raise \"Unsupported architecture\"\n    end\n  else\n      raise \"Unsupported\
      \ operating system\"\n  end\n\n  def install\n    bin.install Dir[\"sentry-cli-*\"\
      ].first => \"sentry-cli\"\n  end\n\n  test do\n    assert_match version.to_s,\
      \ shell_output(\"#{bin}/sentry-cli --version\").chomp\n  end\nend\n"
  - name: github
    includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
  - name: registry
    apps:
      app:sentry-cli:
        urlTemplate: https://downloads.sentry-cdn.com/sentry-cli/{{version}}/{{file}}
        includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
        checksums:
          - algorithm: sha256
            format: hex
requireNames:
  - /^sentry-cli-Darwin-x86_64$/
  - /^sentry-cli-Darwin-arm64$/
  - /^sentry-cli-Darwin-universal$/
  - /^sentry-cli-Linux-i686$/
  - /^sentry-cli-Linux-x86_64$/
  - /^sentry-cli-Linux-armv7$/
  - /^sentry-cli-Linux-aarch64$/
  - /^sentry-cli-Windows-i686.exe$/
  - /^sentry-cli-Windows-x86_64.exe$/
